# Generated by Django 4.0.3 on 2022-03-28 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_rating_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='TheUser',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
