# Generated by Django 4.0.3 on 2022-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_date_review_theuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='MovieTitle',
            field=models.TextField(default='no title'),
        ),
    ]
